-- MySQL Script generated by MySQL Workbench
-- Sun Nov  7 13:40:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(30) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `pass` VARCHAR(60) NOT NULL,
  `picture` VARCHAR(50) NULL,
  `rights` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `articles` ;

CREATE TABLE IF NOT EXISTS `articles` (
  `id_article` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `genre` VARCHAR(50) NOT NULL,
  `game` VARCHAR(100) NOT NULL,
  `abstract` VARCHAR(2000) NOT NULL,
  `filepath` VARCHAR(50) NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_article`),
  INDEX `fk_articles_users_idx` (`id_user` ASC),
  CONSTRAINT `fk_articles_users`
    FOREIGN KEY (`id_user`)
    REFERENCES `users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ratings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ratings` ;

CREATE TABLE IF NOT EXISTS `ratings` (
  `id_rating` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_article` INT NOT NULL,
  `rating` INT NOT NULL,
  `comment` VARCHAR(500) NULL,
  PRIMARY KEY (`id_rating`),
  INDEX `fk_ratings_users_idx` (`id_user` ASC),
  INDEX `fk_ratings_articles_idx` (`id_article` ASC),
  CONSTRAINT `fk_ratings_users`
    FOREIGN KEY (`id_user`)
    REFERENCES `users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ratings_articles`
    FOREIGN KEY (`id_article`)
    REFERENCES `articles` (`id_article`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `users`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `users` (`id_user`, `login`, `email`, `pass`, `rights`) VALUES (1, 'SuperAdmin', 'SuperAdmin@admin.cz', 'admin', 10);
INSERT INTO `users` (`id_user`, `login`, `email`, `pass`, `rights`) VALUES (2, 'Admin', 'Admin@admin.cz', 'admin', 5);
INSERT INTO `users` (`id_user`, `login`, `email`, `pass`, `rights`) VALUES (3, 'Recenzent1', 'Pepik@seznam.cz', 'recenzent', 3);
INSERT INTO `users` (`id_user`, `login`, `email`, `pass`, `rights`) VALUES (4, 'Autor1', 'Tomas@google.com', 'autor', 1);
INSERT INTO `users` (`id_user`, `login`, `email`, `pass`, `rights`) VALUES (5, 'AutorProDelete', 'deleteme@delete.org', 'autor', 1);

COMMIT;

